name: Jikkosoft App

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Validate Dockerfile syntax
      run: docker build -t test-app .

    - name: Run simple HTTP test
      run: |
        docker run -d -p 8080:80 test-app
        sleep 5
        curl -v http://localhost:8080
